### ISSUE TITLE
network access is not always disallowed by default

### ISSUE THREAD

**Issue by velle** [martin7th/xmlstarlet-notes#2]
From https://martin7th.github.io/xmlstarlet-notes/#global-opt-net:

> For security, network access is disallowed by default

I'm on `Ubuntu 22.04.4 LTS` and installed with `apt install xmlstarlet`. By default it will in fact download xml schemas over the internet, and thus `--net` makes no difference. 

```
$ xmlstarlet --version
1.6.1
compiled against libxml2 2.9.10, linked with 20913
compiled against libxslt 1.1.34, linked with 10134
```

When using xmllint the default is _also_ that internet download is allowed, but there is a `--nonet` option that can be set.

**Comment by velle** [comment]
I know, from the other issue, that this is not a support forum. But what about this kind of issue, where something may be slightly incorrect in your notes. Are you interested in knowing?

I am currently digging deeper into why my installation defaults to using the internet (when it seems that it behaves differently for others), and I was planning on updating this issue when I have found out. But if you have no interest and think it does not belong here, then please just close this issue :)

**Comment by martin7th** [comment]
My personal notes were made for my own benefit and I don't aim for completeness. I share them because `xmlstarlet` documentation is rudimentary. If you have an issue why not post it where people or search engines will look for it, e.g. `xmlstarlet`'s [homepage](https://sourceforge.net/p/xmlstar/_list/tickets) or a StackExchange forum.
